# Generated by Django 4.0 on 2022-01-06 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_user_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
