# Generated by Django 4.0 on 2022-01-06 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_user_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
